### ISSUE TITLE
Does not work for custom actions defined in own catkin workspace

### ISSUE THREAD

**Issue by koenlek** [OTL/rqt_ez_publisher#14]
Hi,

I have specified an action in my own workspace here:
/home/koenlek/hydro_catkin/src/semantic_turtle_meta/st_navigation/action/GotoNode.action

This automatically generates to related messages here:
/home/koenlek/hydro_catkin/devel/share/st_navigation/msg/GotoNodeAction[subaction_type].msg

However, your plugin throws an error when I want to publish to e.g. /move_base_topo/goal the error is: 
IOError: [Errno 2] No such file or directory: u'/home/koenlek/hydro_catkin/src/semantic_turtle_meta/st_navigation/msg/GotoNodeActionGoal.msg'

Clearly, it is looking in the wrong directory. Maybe make sure to also look into the devel folder (I would suggest to first try src, then devel, then install, and only continue looking if the current failed)?

**Comment by OTL** [comment]
Thanks.

In devel environment, it does not work.
It seems to be a problem of actionlib and roslib.

But if you use install environment it seems to work successfully, in my environment.

I will check more detail, but if you can use install environment, please try it.

**Comment by OTL** [comment]
I pushed a commit to support action in devel environment.
Please try it if you can.

BUT rqt_ez_publisher its self works on only _install_ environment.
So, your choice is
1. wait until released rqt_ez_publisher 0.3.0
2. install rqt_ez_publisher in other workspace

If you kindly try to choice 2, please make two catkin workspace.
one for rqt_ez_publisher, one for your devel.
(you have to create your devel workspace after install workspace)

**Comment by OTL** [comment]
Supported in v0.3.0
