### ISSUE TITLE
v0.3.1 problem

### ISSUE THREAD

**Issue by fmina** [OTL/rqt_ez_publisher#22]
I am trying to publish a topic of type joint_trajectory http://docs.ros.org/jade/api/trajectory_msgs/html/msg/JointTrajectory.html and a node is correctly subscribing to the topic. This worked perfectly with v0.3.0 but since v0.3.1 the tool fails to show the topic attributes with the following error:

`[WARN] [WallTime: 1462037896.472686] 'positions' is not in list`
`File "/opt/ros/indigo/lib/python2.7/dist-packages/rqt_ez_publisher/ez_publisher_widget.py", line 102, in add_slider_by_text
    self.add_slider_by_text(string)`

I tried v0.3.0 and it worked well, so I think it is an issue with the new version. 

Thanks!

**Comment by OTL** [comment]
Thank you for giving feedback!

It seems that this is side effect of #17.
I'll check it soon.

**Comment by OTL** [comment]
Fixed!! I'm happy if you could try new version!
(indigo-devel or jade-devel)
It will be released next sync.

**Comment by OTL** [comment]
I believe this is fixed in v0.3.2
