### ISSUE TITLE
Is it possible to rename the window title?

### ISSUE THREAD

**Issue by felixduvallet** [OTL/rqt_ez_publisher#24]
When starting rqt_ez_publisher directly (i.e., `rosrun rqt_ez_publisher rqt_ez_publisher`) the window title is always `rqt_ez_publisher__EzPublisher - rqt`.

Is there a way to change this? I started exploring your code (you set the widget title when running it inside `rqt`), but got pretty far into the `qt_gui` code before getting super lost.

**Comment by OTL** [comment]
I believe this is the behaviour of rqt, and I don't know how to control.
