### ISSUE TITLE
rqt_ez_publisher not found in melodic distro

### ISSUE THREAD

**Issue by NishanthARao** [OTL/rqt_ez_publisher#29]

**Comment by NishanthARao** [comment]
Hello.

This package has been removed in melodic distro. However, i am in need of this package. Could you please fix this issure / provide any alternatives? I am a beginner to ROS.

Thank you .

**Comment by OTL** [comment]
Thank you for feedback! I'll upload soon.

**Comment by OTL** [comment]
I did bloom-release for melodic. It will be released next sync!
I guess that you can use this package from source if you can.
(But the default branch was old (for indigo), and I changed to melodic. If you have already tried, please remove the source and try again.)

**Comment by NishanthARao** [comment]
I'm extremely thankful to you, sir.

If I face any issue, I ll let you know.

Thanks a tonn

**Comment by OTL** [comment]
released!
